name: Bug Report
description: Reporting an error or unexpected behaviour
labels: unconfirmed bug
body:
  - type: markdown
    attributes:
      value: >
        Please note that this form is for reporting bugs only!
  - type: input
    attributes:
      label: Summary
      description: A general overview of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What was done to cause the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code/Example
      description: >
        The specific code that caused the bug, if applicable.
      render: python
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What should have happened without the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Information
      description: >
        OS and Python version if applicable
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please ensure you have met all these checkboxes before creating the issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
